#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DoiCTXH")]
	public partial class DoiCTXHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBan(Ban instance);
    partial void UpdateBan(Ban instance);
    partial void DeleteBan(Ban instance);
    partial void InsertBanDieuhanh(BanDieuhanh instance);
    partial void UpdateBanDieuhanh(BanDieuhanh instance);
    partial void DeleteBanDieuhanh(BanDieuhanh instance);
    partial void InsertChuongtrinh(Chuongtrinh instance);
    partial void UpdateChuongtrinh(Chuongtrinh instance);
    partial void DeleteChuongtrinh(Chuongtrinh instance);
    partial void InsertKho(Kho instance);
    partial void UpdateKho(Kho instance);
    partial void DeleteKho(Kho instance);
    partial void InsertKhoa(Khoa instance);
    partial void UpdateKhoa(Khoa instance);
    partial void DeleteKhoa(Khoa instance);
    partial void InsertKhoadoivien(Khoadoivien instance);
    partial void UpdateKhoadoivien(Khoadoivien instance);
    partial void DeleteKhoadoivien(Khoadoivien instance);
    partial void InsertThamgiaBan(ThamgiaBan instance);
    partial void UpdateThamgiaBan(ThamgiaBan instance);
    partial void DeleteThamgiaBan(ThamgiaBan instance);
    partial void InsertThamgiaBDH(ThamgiaBDH instance);
    partial void UpdateThamgiaBDH(ThamgiaBDH instance);
    partial void DeleteThamgiaBDH(ThamgiaBDH instance);
    partial void InsertThamgiachuongtrinh(Thamgiachuongtrinh instance);
    partial void UpdateThamgiachuongtrinh(Thamgiachuongtrinh instance);
    partial void DeleteThamgiachuongtrinh(Thamgiachuongtrinh instance);
    partial void InsertThanhvien(Thanhvien instance);
    partial void UpdateThanhvien(Thanhvien instance);
    partial void DeleteThanhvien(Thanhvien instance);
    partial void InsertUserLog(UserLog instance);
    partial void UpdateUserLog(UserLog instance);
    partial void DeleteUserLog(UserLog instance);
    #endregion
		
		public DoiCTXHDataContext() : 
				base(global::DoAnCNPM.Properties.Settings.Default.DoiCTXHConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DoiCTXHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoiCTXHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoiCTXHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoiCTXHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ban> Bans
		{
			get
			{
				return this.GetTable<Ban>();
			}
		}
		
		public System.Data.Linq.Table<BanDieuhanh> BanDieuhanhs
		{
			get
			{
				return this.GetTable<BanDieuhanh>();
			}
		}
		
		public System.Data.Linq.Table<Chuongtrinh> Chuongtrinhs
		{
			get
			{
				return this.GetTable<Chuongtrinh>();
			}
		}
		
		public System.Data.Linq.Table<Image> Images
		{
			get
			{
				return this.GetTable<Image>();
			}
		}
		
		public System.Data.Linq.Table<Kho> Khos
		{
			get
			{
				return this.GetTable<Kho>();
			}
		}
		
		public System.Data.Linq.Table<Khoa> Khoas
		{
			get
			{
				return this.GetTable<Khoa>();
			}
		}
		
		public System.Data.Linq.Table<Khoadoivien> Khoadoiviens
		{
			get
			{
				return this.GetTable<Khoadoivien>();
			}
		}
		
		public System.Data.Linq.Table<ThamgiaBan> ThamgiaBans
		{
			get
			{
				return this.GetTable<ThamgiaBan>();
			}
		}
		
		public System.Data.Linq.Table<ThamgiaBDH> ThamgiaBDHs
		{
			get
			{
				return this.GetTable<ThamgiaBDH>();
			}
		}
		
		public System.Data.Linq.Table<Thamgiachuongtrinh> Thamgiachuongtrinhs
		{
			get
			{
				return this.GetTable<Thamgiachuongtrinh>();
			}
		}
		
		public System.Data.Linq.Table<Thanhvien> Thanhviens
		{
			get
			{
				return this.GetTable<Thanhvien>();
			}
		}
		
		public System.Data.Linq.Table<UserLog> UserLogs
		{
			get
			{
				return this.GetTable<UserLog>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_test")]
		public int sp_test([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] ref string chuoi_tra_ve)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), chuoi_tra_ve);
			chuoi_tra_ve = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ThemThanhVien")]
		public void sp_ThemThanhVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="return", DbType="Int")] ref System.Nullable<int> @return, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSSV", DbType="NVarChar(15)")] string mSSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hoten", DbType="NVarChar(30)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngaysinh", DbType="Date")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quequan", DbType="NVarChar(30)")] string quequan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nganh", DbType="NVarChar(30)")] string nganh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Khoa", DbType="NVarChar(15)")] string khoa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KhoaDV", DbType="NVarChar(15)")] string khoaDV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), @return, mSSV, hoten, ngaysinh, quequan, nganh, khoa, khoaDV);
			@return = ((System.Nullable<int>)(result.GetParameterValue(0)));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_TimKiemTV")]
		public void Sp_TimKiemTV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ma", DbType="NVarChar(30)")] string ma)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.upt_ThanhVien")]
		public void upt_ThanhVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSSV", DbType="NVarChar(30)")] string mSSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hoten", DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngaysinh", DbType="Date")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quequan", DbType="NVarChar(30)")] string quequan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nganh", DbType="NVarChar(30)")] string nganh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Khoa", DbType="NVarChar(30)")] string khoa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KhoaDV", DbType="NVarChar(30)")] string khoaDV)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mSSV, hoten, ngaysinh, quequan, nganh, khoa, khoaDV);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_SoDV")]
		public int usp_SoDV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KhoaDV", DbType="NVarChar(30)")] string khoaDV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Soluong", DbType="Int")] ref System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), khoaDV, soluong);
			soluong = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fu_DS_DoivienTheoKDV", IsComposable=true)]
		public IQueryable<fu_DS_DoivienTheoKDVResult> fu_DS_DoivienTheoKDV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KhoaDv", DbType="NVarChar(10)")] string khoaDv)
		{
			return this.CreateMethodCallQuery<fu_DS_DoivienTheoKDVResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), khoaDv);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ban")]
	public partial class Ban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_ban;
		
		private string _Tenban;
		
		private System.Nullable<System.DateTime> _Ngaythanhlap;
		
		private EntitySet<ThamgiaBan> _ThamgiaBans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_banChanging(string value);
    partial void OnMa_banChanged();
    partial void OnTenbanChanging(string value);
    partial void OnTenbanChanged();
    partial void OnNgaythanhlapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaythanhlapChanged();
    #endregion
		
		public Ban()
		{
			this._ThamgiaBans = new EntitySet<ThamgiaBan>(new Action<ThamgiaBan>(this.attach_ThamgiaBans), new Action<ThamgiaBan>(this.detach_ThamgiaBans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_ban", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_ban
		{
			get
			{
				return this._Ma_ban;
			}
			set
			{
				if ((this._Ma_ban != value))
				{
					this.OnMa_banChanging(value);
					this.SendPropertyChanging();
					this._Ma_ban = value;
					this.SendPropertyChanged("Ma_ban");
					this.OnMa_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenban", DbType="NVarChar(50)")]
		public string Tenban
		{
			get
			{
				return this._Tenban;
			}
			set
			{
				if ((this._Tenban != value))
				{
					this.OnTenbanChanging(value);
					this.SendPropertyChanging();
					this._Tenban = value;
					this.SendPropertyChanged("Tenban");
					this.OnTenbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaythanhlap", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaythanhlap
		{
			get
			{
				return this._Ngaythanhlap;
			}
			set
			{
				if ((this._Ngaythanhlap != value))
				{
					this.OnNgaythanhlapChanging(value);
					this.SendPropertyChanging();
					this._Ngaythanhlap = value;
					this.SendPropertyChanged("Ngaythanhlap");
					this.OnNgaythanhlapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_ThamgiaBan", Storage="_ThamgiaBans", ThisKey="Ma_ban", OtherKey="Ma_ban")]
		public EntitySet<ThamgiaBan> ThamgiaBans
		{
			get
			{
				return this._ThamgiaBans;
			}
			set
			{
				this._ThamgiaBans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThamgiaBans(ThamgiaBan entity)
		{
			this.SendPropertyChanging();
			entity.Ban = this;
		}
		
		private void detach_ThamgiaBans(ThamgiaBan entity)
		{
			this.SendPropertyChanging();
			entity.Ban = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BanDieuhanh")]
	public partial class BanDieuhanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NhiemKy;
		
		private System.Nullable<System.DateTime> _Ngaybatdau;
		
		private EntitySet<ThamgiaBDH> _ThamgiaBDHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNhiemKyChanging(int value);
    partial void OnNhiemKyChanged();
    partial void OnNgaybatdauChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaybatdauChanged();
    #endregion
		
		public BanDieuhanh()
		{
			this._ThamgiaBDHs = new EntitySet<ThamgiaBDH>(new Action<ThamgiaBDH>(this.attach_ThamgiaBDHs), new Action<ThamgiaBDH>(this.detach_ThamgiaBDHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhiemKy", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int NhiemKy
		{
			get
			{
				return this._NhiemKy;
			}
			set
			{
				if ((this._NhiemKy != value))
				{
					this.OnNhiemKyChanging(value);
					this.SendPropertyChanging();
					this._NhiemKy = value;
					this.SendPropertyChanged("NhiemKy");
					this.OnNhiemKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaybatdau", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaybatdau
		{
			get
			{
				return this._Ngaybatdau;
			}
			set
			{
				if ((this._Ngaybatdau != value))
				{
					this.OnNgaybatdauChanging(value);
					this.SendPropertyChanging();
					this._Ngaybatdau = value;
					this.SendPropertyChanged("Ngaybatdau");
					this.OnNgaybatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BanDieuhanh_ThamgiaBDH", Storage="_ThamgiaBDHs", ThisKey="NhiemKy", OtherKey="Nhiemky")]
		public EntitySet<ThamgiaBDH> ThamgiaBDHs
		{
			get
			{
				return this._ThamgiaBDHs;
			}
			set
			{
				this._ThamgiaBDHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThamgiaBDHs(ThamgiaBDH entity)
		{
			this.SendPropertyChanging();
			entity.BanDieuhanh = this;
		}
		
		private void detach_ThamgiaBDHs(ThamgiaBDH entity)
		{
			this.SendPropertyChanging();
			entity.BanDieuhanh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chuongtrinh")]
	public partial class Chuongtrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_CT;
		
		private string _TenCT;
		
		private System.Nullable<System.DateTime> _Ngaytochuc;
		
		private string _Diadiem;
		
		private System.Nullable<int> _Kinhphi;
		
		private System.Nullable<int> _DiemCTXH;
		
		private EntitySet<Thamgiachuongtrinh> _Thamgiachuongtrinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_CTChanging(string value);
    partial void OnMa_CTChanged();
    partial void OnTenCTChanging(string value);
    partial void OnTenCTChanged();
    partial void OnNgaytochucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaytochucChanged();
    partial void OnDiadiemChanging(string value);
    partial void OnDiadiemChanged();
    partial void OnKinhphiChanging(System.Nullable<int> value);
    partial void OnKinhphiChanged();
    partial void OnDiemCTXHChanging(System.Nullable<int> value);
    partial void OnDiemCTXHChanged();
    #endregion
		
		public Chuongtrinh()
		{
			this._Thamgiachuongtrinhs = new EntitySet<Thamgiachuongtrinh>(new Action<Thamgiachuongtrinh>(this.attach_Thamgiachuongtrinhs), new Action<Thamgiachuongtrinh>(this.detach_Thamgiachuongtrinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_CT", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_CT
		{
			get
			{
				return this._Ma_CT;
			}
			set
			{
				if ((this._Ma_CT != value))
				{
					this.OnMa_CTChanging(value);
					this.SendPropertyChanging();
					this._Ma_CT = value;
					this.SendPropertyChanged("Ma_CT");
					this.OnMa_CTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCT", DbType="NVarChar(50)")]
		public string TenCT
		{
			get
			{
				return this._TenCT;
			}
			set
			{
				if ((this._TenCT != value))
				{
					this.OnTenCTChanging(value);
					this.SendPropertyChanging();
					this._TenCT = value;
					this.SendPropertyChanged("TenCT");
					this.OnTenCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaytochuc", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaytochuc
		{
			get
			{
				return this._Ngaytochuc;
			}
			set
			{
				if ((this._Ngaytochuc != value))
				{
					this.OnNgaytochucChanging(value);
					this.SendPropertyChanging();
					this._Ngaytochuc = value;
					this.SendPropertyChanged("Ngaytochuc");
					this.OnNgaytochucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diadiem", DbType="NVarChar(50)")]
		public string Diadiem
		{
			get
			{
				return this._Diadiem;
			}
			set
			{
				if ((this._Diadiem != value))
				{
					this.OnDiadiemChanging(value);
					this.SendPropertyChanging();
					this._Diadiem = value;
					this.SendPropertyChanged("Diadiem");
					this.OnDiadiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kinhphi", DbType="Int")]
		public System.Nullable<int> Kinhphi
		{
			get
			{
				return this._Kinhphi;
			}
			set
			{
				if ((this._Kinhphi != value))
				{
					this.OnKinhphiChanging(value);
					this.SendPropertyChanging();
					this._Kinhphi = value;
					this.SendPropertyChanged("Kinhphi");
					this.OnKinhphiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCTXH", DbType="Int")]
		public System.Nullable<int> DiemCTXH
		{
			get
			{
				return this._DiemCTXH;
			}
			set
			{
				if ((this._DiemCTXH != value))
				{
					this.OnDiemCTXHChanging(value);
					this.SendPropertyChanging();
					this._DiemCTXH = value;
					this.SendPropertyChanged("DiemCTXH");
					this.OnDiemCTXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chuongtrinh_Thamgiachuongtrinh", Storage="_Thamgiachuongtrinhs", ThisKey="Ma_CT", OtherKey="Ma_CT")]
		public EntitySet<Thamgiachuongtrinh> Thamgiachuongtrinhs
		{
			get
			{
				return this._Thamgiachuongtrinhs;
			}
			set
			{
				this._Thamgiachuongtrinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thamgiachuongtrinhs(Thamgiachuongtrinh entity)
		{
			this.SendPropertyChanging();
			entity.Chuongtrinh = this;
		}
		
		private void detach_Thamgiachuongtrinhs(Thamgiachuongtrinh entity)
		{
			this.SendPropertyChanging();
			entity.Chuongtrinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Images")]
	public partial class Image
	{
		
		private string _Url;
		
		private string _Ghichu;
		
		public Image()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(1000)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(50)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this._Ghichu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kho")]
	public partial class Kho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_VD;
		
		private string _TenVD;
		
		private string _Donvi;
		
		private System.Nullable<int> _Soluong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_VDChanging(string value);
    partial void OnMa_VDChanged();
    partial void OnTenVDChanging(string value);
    partial void OnTenVDChanged();
    partial void OnDonviChanging(string value);
    partial void OnDonviChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    #endregion
		
		public Kho()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_VD", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_VD
		{
			get
			{
				return this._Ma_VD;
			}
			set
			{
				if ((this._Ma_VD != value))
				{
					this.OnMa_VDChanging(value);
					this.SendPropertyChanging();
					this._Ma_VD = value;
					this.SendPropertyChanged("Ma_VD");
					this.OnMa_VDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVD", DbType="NVarChar(50)")]
		public string TenVD
		{
			get
			{
				return this._TenVD;
			}
			set
			{
				if ((this._TenVD != value))
				{
					this.OnTenVDChanging(value);
					this.SendPropertyChanging();
					this._TenVD = value;
					this.SendPropertyChanged("TenVD");
					this.OnTenVDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donvi", DbType="NVarChar(15)")]
		public string Donvi
		{
			get
			{
				return this._Donvi;
			}
			set
			{
				if ((this._Donvi != value))
				{
					this.OnDonviChanging(value);
					this.SendPropertyChanging();
					this._Donvi = value;
					this.SendPropertyChanged("Donvi");
					this.OnDonviChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoa")]
	public partial class Khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Khoa;
		
		private string _Ten_Khoa;
		
		private System.Nullable<System.DateTime> _NgayThanhlap;
		
		private EntitySet<Thanhvien> _Thanhviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_KhoaChanging(string value);
    partial void OnMa_KhoaChanged();
    partial void OnTen_KhoaChanging(string value);
    partial void OnTen_KhoaChanged();
    partial void OnNgayThanhlapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThanhlapChanged();
    #endregion
		
		public Khoa()
		{
			this._Thanhviens = new EntitySet<Thanhvien>(new Action<Thanhvien>(this.attach_Thanhviens), new Action<Thanhvien>(this.detach_Thanhviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Khoa", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Khoa
		{
			get
			{
				return this._Ma_Khoa;
			}
			set
			{
				if ((this._Ma_Khoa != value))
				{
					this.OnMa_KhoaChanging(value);
					this.SendPropertyChanging();
					this._Ma_Khoa = value;
					this.SendPropertyChanged("Ma_Khoa");
					this.OnMa_KhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Khoa", DbType="NVarChar(50)")]
		public string Ten_Khoa
		{
			get
			{
				return this._Ten_Khoa;
			}
			set
			{
				if ((this._Ten_Khoa != value))
				{
					this.OnTen_KhoaChanging(value);
					this.SendPropertyChanging();
					this._Ten_Khoa = value;
					this.SendPropertyChanged("Ten_Khoa");
					this.OnTen_KhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhlap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThanhlap
		{
			get
			{
				return this._NgayThanhlap;
			}
			set
			{
				if ((this._NgayThanhlap != value))
				{
					this.OnNgayThanhlapChanging(value);
					this.SendPropertyChanging();
					this._NgayThanhlap = value;
					this.SendPropertyChanged("NgayThanhlap");
					this.OnNgayThanhlapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_Thanhvien", Storage="_Thanhviens", ThisKey="Ma_Khoa", OtherKey="Khoa")]
		public EntitySet<Thanhvien> Thanhviens
		{
			get
			{
				return this._Thanhviens;
			}
			set
			{
				this._Thanhviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thanhviens(Thanhvien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa1 = this;
		}
		
		private void detach_Thanhviens(Thanhvien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoadoivien")]
	public partial class Khoadoivien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Khoa;
		
		private System.Nullable<System.DateTime> _Ngayketnap;
		
		private EntitySet<Thanhvien> _Thanhviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_KhoaChanging(string value);
    partial void OnMa_KhoaChanged();
    partial void OnNgayketnapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayketnapChanged();
    #endregion
		
		public Khoadoivien()
		{
			this._Thanhviens = new EntitySet<Thanhvien>(new Action<Thanhvien>(this.attach_Thanhviens), new Action<Thanhvien>(this.detach_Thanhviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Khoa", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Khoa
		{
			get
			{
				return this._Ma_Khoa;
			}
			set
			{
				if ((this._Ma_Khoa != value))
				{
					this.OnMa_KhoaChanging(value);
					this.SendPropertyChanging();
					this._Ma_Khoa = value;
					this.SendPropertyChanged("Ma_Khoa");
					this.OnMa_KhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayketnap", DbType="Date")]
		public System.Nullable<System.DateTime> Ngayketnap
		{
			get
			{
				return this._Ngayketnap;
			}
			set
			{
				if ((this._Ngayketnap != value))
				{
					this.OnNgayketnapChanging(value);
					this.SendPropertyChanging();
					this._Ngayketnap = value;
					this.SendPropertyChanged("Ngayketnap");
					this.OnNgayketnapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoadoivien_Thanhvien", Storage="_Thanhviens", ThisKey="Ma_Khoa", OtherKey="KhoaDV")]
		public EntitySet<Thanhvien> Thanhviens
		{
			get
			{
				return this._Thanhviens;
			}
			set
			{
				this._Thanhviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thanhviens(Thanhvien entity)
		{
			this.SendPropertyChanging();
			entity.Khoadoivien = this;
		}
		
		private void detach_Thanhviens(Thanhvien entity)
		{
			this.SendPropertyChanging();
			entity.Khoadoivien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThamgiaBan")]
	public partial class ThamgiaBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_ban;
		
		private string _Ma_SV;
		
		private EntityRef<Ban> _Ban;
		
		private EntityRef<Thanhvien> _Thanhvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_banChanging(string value);
    partial void OnMa_banChanged();
    partial void OnMa_SVChanging(string value);
    partial void OnMa_SVChanged();
    #endregion
		
		public ThamgiaBan()
		{
			this._Ban = default(EntityRef<Ban>);
			this._Thanhvien = default(EntityRef<Thanhvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_ban", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_ban
		{
			get
			{
				return this._Ma_ban;
			}
			set
			{
				if ((this._Ma_ban != value))
				{
					if (this._Ban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_banChanging(value);
					this.SendPropertyChanging();
					this._Ma_ban = value;
					this.SendPropertyChanged("Ma_ban");
					this.OnMa_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SV", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_SV
		{
			get
			{
				return this._Ma_SV;
			}
			set
			{
				if ((this._Ma_SV != value))
				{
					if (this._Thanhvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_SVChanging(value);
					this.SendPropertyChanging();
					this._Ma_SV = value;
					this.SendPropertyChanged("Ma_SV");
					this.OnMa_SVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_ThamgiaBan", Storage="_Ban", ThisKey="Ma_ban", OtherKey="Ma_ban", IsForeignKey=true)]
		public Ban Ban
		{
			get
			{
				return this._Ban.Entity;
			}
			set
			{
				Ban previousValue = this._Ban.Entity;
				if (((previousValue != value) 
							|| (this._Ban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ban.Entity = null;
						previousValue.ThamgiaBans.Remove(this);
					}
					this._Ban.Entity = value;
					if ((value != null))
					{
						value.ThamgiaBans.Add(this);
						this._Ma_ban = value.Ma_ban;
					}
					else
					{
						this._Ma_ban = default(string);
					}
					this.SendPropertyChanged("Ban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thanhvien_ThamgiaBan", Storage="_Thanhvien", ThisKey="Ma_SV", OtherKey="Ma_SV", IsForeignKey=true)]
		public Thanhvien Thanhvien
		{
			get
			{
				return this._Thanhvien.Entity;
			}
			set
			{
				Thanhvien previousValue = this._Thanhvien.Entity;
				if (((previousValue != value) 
							|| (this._Thanhvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thanhvien.Entity = null;
						previousValue.ThamgiaBans.Remove(this);
					}
					this._Thanhvien.Entity = value;
					if ((value != null))
					{
						value.ThamgiaBans.Add(this);
						this._Ma_SV = value.Ma_SV;
					}
					else
					{
						this._Ma_SV = default(string);
					}
					this.SendPropertyChanged("Thanhvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThamgiaBDH")]
	public partial class ThamgiaBDH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_SV;
		
		private int _Nhiemky;
		
		private string _Chucvu;
		
		private EntityRef<BanDieuhanh> _BanDieuhanh;
		
		private EntityRef<Thanhvien> _Thanhvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_SVChanging(string value);
    partial void OnMa_SVChanged();
    partial void OnNhiemkyChanging(int value);
    partial void OnNhiemkyChanged();
    partial void OnChucvuChanging(string value);
    partial void OnChucvuChanged();
    #endregion
		
		public ThamgiaBDH()
		{
			this._BanDieuhanh = default(EntityRef<BanDieuhanh>);
			this._Thanhvien = default(EntityRef<Thanhvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SV", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_SV
		{
			get
			{
				return this._Ma_SV;
			}
			set
			{
				if ((this._Ma_SV != value))
				{
					if (this._Thanhvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_SVChanging(value);
					this.SendPropertyChanging();
					this._Ma_SV = value;
					this.SendPropertyChanged("Ma_SV");
					this.OnMa_SVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhiemky", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Nhiemky
		{
			get
			{
				return this._Nhiemky;
			}
			set
			{
				if ((this._Nhiemky != value))
				{
					if (this._BanDieuhanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhiemkyChanging(value);
					this.SendPropertyChanging();
					this._Nhiemky = value;
					this.SendPropertyChanged("Nhiemky");
					this.OnNhiemkyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chucvu", DbType="NVarChar(30)")]
		public string Chucvu
		{
			get
			{
				return this._Chucvu;
			}
			set
			{
				if ((this._Chucvu != value))
				{
					this.OnChucvuChanging(value);
					this.SendPropertyChanging();
					this._Chucvu = value;
					this.SendPropertyChanged("Chucvu");
					this.OnChucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BanDieuhanh_ThamgiaBDH", Storage="_BanDieuhanh", ThisKey="Nhiemky", OtherKey="NhiemKy", IsForeignKey=true)]
		public BanDieuhanh BanDieuhanh
		{
			get
			{
				return this._BanDieuhanh.Entity;
			}
			set
			{
				BanDieuhanh previousValue = this._BanDieuhanh.Entity;
				if (((previousValue != value) 
							|| (this._BanDieuhanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BanDieuhanh.Entity = null;
						previousValue.ThamgiaBDHs.Remove(this);
					}
					this._BanDieuhanh.Entity = value;
					if ((value != null))
					{
						value.ThamgiaBDHs.Add(this);
						this._Nhiemky = value.NhiemKy;
					}
					else
					{
						this._Nhiemky = default(int);
					}
					this.SendPropertyChanged("BanDieuhanh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thanhvien_ThamgiaBDH", Storage="_Thanhvien", ThisKey="Ma_SV", OtherKey="Ma_SV", IsForeignKey=true)]
		public Thanhvien Thanhvien
		{
			get
			{
				return this._Thanhvien.Entity;
			}
			set
			{
				Thanhvien previousValue = this._Thanhvien.Entity;
				if (((previousValue != value) 
							|| (this._Thanhvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thanhvien.Entity = null;
						previousValue.ThamgiaBDHs.Remove(this);
					}
					this._Thanhvien.Entity = value;
					if ((value != null))
					{
						value.ThamgiaBDHs.Add(this);
						this._Ma_SV = value.Ma_SV;
					}
					else
					{
						this._Ma_SV = default(string);
					}
					this.SendPropertyChanged("Thanhvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thamgiachuongtrinh")]
	public partial class Thamgiachuongtrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_CT;
		
		private string _Ma_SV;
		
		private System.Nullable<int> _DiemCTXH;
		
		private string _Danhgia;
		
		private EntityRef<Chuongtrinh> _Chuongtrinh;
		
		private EntityRef<Thanhvien> _Thanhvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_CTChanging(string value);
    partial void OnMa_CTChanged();
    partial void OnMa_SVChanging(string value);
    partial void OnMa_SVChanged();
    partial void OnDiemCTXHChanging(System.Nullable<int> value);
    partial void OnDiemCTXHChanged();
    partial void OnDanhgiaChanging(string value);
    partial void OnDanhgiaChanged();
    #endregion
		
		public Thamgiachuongtrinh()
		{
			this._Chuongtrinh = default(EntityRef<Chuongtrinh>);
			this._Thanhvien = default(EntityRef<Thanhvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_CT", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_CT
		{
			get
			{
				return this._Ma_CT;
			}
			set
			{
				if ((this._Ma_CT != value))
				{
					if (this._Chuongtrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_CTChanging(value);
					this.SendPropertyChanging();
					this._Ma_CT = value;
					this.SendPropertyChanged("Ma_CT");
					this.OnMa_CTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SV", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_SV
		{
			get
			{
				return this._Ma_SV;
			}
			set
			{
				if ((this._Ma_SV != value))
				{
					if (this._Thanhvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_SVChanging(value);
					this.SendPropertyChanging();
					this._Ma_SV = value;
					this.SendPropertyChanged("Ma_SV");
					this.OnMa_SVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCTXH", DbType="Int")]
		public System.Nullable<int> DiemCTXH
		{
			get
			{
				return this._DiemCTXH;
			}
			set
			{
				if ((this._DiemCTXH != value))
				{
					this.OnDiemCTXHChanging(value);
					this.SendPropertyChanging();
					this._DiemCTXH = value;
					this.SendPropertyChanged("DiemCTXH");
					this.OnDiemCTXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Danhgia", DbType="NVarChar(50)")]
		public string Danhgia
		{
			get
			{
				return this._Danhgia;
			}
			set
			{
				if ((this._Danhgia != value))
				{
					this.OnDanhgiaChanging(value);
					this.SendPropertyChanging();
					this._Danhgia = value;
					this.SendPropertyChanged("Danhgia");
					this.OnDanhgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chuongtrinh_Thamgiachuongtrinh", Storage="_Chuongtrinh", ThisKey="Ma_CT", OtherKey="Ma_CT", IsForeignKey=true)]
		public Chuongtrinh Chuongtrinh
		{
			get
			{
				return this._Chuongtrinh.Entity;
			}
			set
			{
				Chuongtrinh previousValue = this._Chuongtrinh.Entity;
				if (((previousValue != value) 
							|| (this._Chuongtrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Chuongtrinh.Entity = null;
						previousValue.Thamgiachuongtrinhs.Remove(this);
					}
					this._Chuongtrinh.Entity = value;
					if ((value != null))
					{
						value.Thamgiachuongtrinhs.Add(this);
						this._Ma_CT = value.Ma_CT;
					}
					else
					{
						this._Ma_CT = default(string);
					}
					this.SendPropertyChanged("Chuongtrinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thanhvien_Thamgiachuongtrinh", Storage="_Thanhvien", ThisKey="Ma_SV", OtherKey="Ma_SV", IsForeignKey=true)]
		public Thanhvien Thanhvien
		{
			get
			{
				return this._Thanhvien.Entity;
			}
			set
			{
				Thanhvien previousValue = this._Thanhvien.Entity;
				if (((previousValue != value) 
							|| (this._Thanhvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thanhvien.Entity = null;
						previousValue.Thamgiachuongtrinhs.Remove(this);
					}
					this._Thanhvien.Entity = value;
					if ((value != null))
					{
						value.Thamgiachuongtrinhs.Add(this);
						this._Ma_SV = value.Ma_SV;
					}
					else
					{
						this._Ma_SV = default(string);
					}
					this.SendPropertyChanged("Thanhvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thanhvien")]
	public partial class Thanhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_SV;
		
		private string _Hoten;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _Quequan;
		
		private string _Nganh;
		
		private string _Khoa;
		
		private string _KhoaDV;
		
		private EntitySet<ThamgiaBan> _ThamgiaBans;
		
		private EntitySet<ThamgiaBDH> _ThamgiaBDHs;
		
		private EntitySet<Thamgiachuongtrinh> _Thamgiachuongtrinhs;
		
		private EntityRef<Khoa> _Khoa1;
		
		private EntityRef<Khoadoivien> _Khoadoivien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_SVChanging(string value);
    partial void OnMa_SVChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnQuequanChanging(string value);
    partial void OnQuequanChanged();
    partial void OnNganhChanging(string value);
    partial void OnNganhChanged();
    partial void OnKhoaChanging(string value);
    partial void OnKhoaChanged();
    partial void OnKhoaDVChanging(string value);
    partial void OnKhoaDVChanged();
    #endregion
		
		public Thanhvien()
		{
			this._ThamgiaBans = new EntitySet<ThamgiaBan>(new Action<ThamgiaBan>(this.attach_ThamgiaBans), new Action<ThamgiaBan>(this.detach_ThamgiaBans));
			this._ThamgiaBDHs = new EntitySet<ThamgiaBDH>(new Action<ThamgiaBDH>(this.attach_ThamgiaBDHs), new Action<ThamgiaBDH>(this.detach_ThamgiaBDHs));
			this._Thamgiachuongtrinhs = new EntitySet<Thamgiachuongtrinh>(new Action<Thamgiachuongtrinh>(this.attach_Thamgiachuongtrinhs), new Action<Thamgiachuongtrinh>(this.detach_Thamgiachuongtrinhs));
			this._Khoa1 = default(EntityRef<Khoa>);
			this._Khoadoivien = default(EntityRef<Khoadoivien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SV", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_SV
		{
			get
			{
				return this._Ma_SV;
			}
			set
			{
				if ((this._Ma_SV != value))
				{
					this.OnMa_SVChanging(value);
					this.SendPropertyChanging();
					this._Ma_SV = value;
					this.SendPropertyChanged("Ma_SV");
					this.OnMa_SVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quequan", DbType="NVarChar(50)")]
		public string Quequan
		{
			get
			{
				return this._Quequan;
			}
			set
			{
				if ((this._Quequan != value))
				{
					this.OnQuequanChanging(value);
					this.SendPropertyChanging();
					this._Quequan = value;
					this.SendPropertyChanged("Quequan");
					this.OnQuequanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nganh", DbType="NVarChar(50)")]
		public string Nganh
		{
			get
			{
				return this._Nganh;
			}
			set
			{
				if ((this._Nganh != value))
				{
					this.OnNganhChanging(value);
					this.SendPropertyChanging();
					this._Nganh = value;
					this.SendPropertyChanged("Nganh");
					this.OnNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="NVarChar(15)")]
		public string Khoa
		{
			get
			{
				return this._Khoa;
			}
			set
			{
				if ((this._Khoa != value))
				{
					if (this._Khoa1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhoaChanging(value);
					this.SendPropertyChanging();
					this._Khoa = value;
					this.SendPropertyChanged("Khoa");
					this.OnKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoaDV", DbType="NVarChar(15)")]
		public string KhoaDV
		{
			get
			{
				return this._KhoaDV;
			}
			set
			{
				if ((this._KhoaDV != value))
				{
					if (this._Khoadoivien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhoaDVChanging(value);
					this.SendPropertyChanging();
					this._KhoaDV = value;
					this.SendPropertyChanged("KhoaDV");
					this.OnKhoaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thanhvien_ThamgiaBan", Storage="_ThamgiaBans", ThisKey="Ma_SV", OtherKey="Ma_SV")]
		public EntitySet<ThamgiaBan> ThamgiaBans
		{
			get
			{
				return this._ThamgiaBans;
			}
			set
			{
				this._ThamgiaBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thanhvien_ThamgiaBDH", Storage="_ThamgiaBDHs", ThisKey="Ma_SV", OtherKey="Ma_SV")]
		public EntitySet<ThamgiaBDH> ThamgiaBDHs
		{
			get
			{
				return this._ThamgiaBDHs;
			}
			set
			{
				this._ThamgiaBDHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thanhvien_Thamgiachuongtrinh", Storage="_Thamgiachuongtrinhs", ThisKey="Ma_SV", OtherKey="Ma_SV")]
		public EntitySet<Thamgiachuongtrinh> Thamgiachuongtrinhs
		{
			get
			{
				return this._Thamgiachuongtrinhs;
			}
			set
			{
				this._Thamgiachuongtrinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_Thanhvien", Storage="_Khoa1", ThisKey="Khoa", OtherKey="Ma_Khoa", IsForeignKey=true)]
		public Khoa Khoa1
		{
			get
			{
				return this._Khoa1.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa1.Entity;
				if (((previousValue != value) 
							|| (this._Khoa1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa1.Entity = null;
						previousValue.Thanhviens.Remove(this);
					}
					this._Khoa1.Entity = value;
					if ((value != null))
					{
						value.Thanhviens.Add(this);
						this._Khoa = value.Ma_Khoa;
					}
					else
					{
						this._Khoa = default(string);
					}
					this.SendPropertyChanged("Khoa1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoadoivien_Thanhvien", Storage="_Khoadoivien", ThisKey="KhoaDV", OtherKey="Ma_Khoa", IsForeignKey=true, DeleteRule="SET NULL")]
		public Khoadoivien Khoadoivien
		{
			get
			{
				return this._Khoadoivien.Entity;
			}
			set
			{
				Khoadoivien previousValue = this._Khoadoivien.Entity;
				if (((previousValue != value) 
							|| (this._Khoadoivien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoadoivien.Entity = null;
						previousValue.Thanhviens.Remove(this);
					}
					this._Khoadoivien.Entity = value;
					if ((value != null))
					{
						value.Thanhviens.Add(this);
						this._KhoaDV = value.Ma_Khoa;
					}
					else
					{
						this._KhoaDV = default(string);
					}
					this.SendPropertyChanged("Khoadoivien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThamgiaBans(ThamgiaBan entity)
		{
			this.SendPropertyChanging();
			entity.Thanhvien = this;
		}
		
		private void detach_ThamgiaBans(ThamgiaBan entity)
		{
			this.SendPropertyChanging();
			entity.Thanhvien = null;
		}
		
		private void attach_ThamgiaBDHs(ThamgiaBDH entity)
		{
			this.SendPropertyChanging();
			entity.Thanhvien = this;
		}
		
		private void detach_ThamgiaBDHs(ThamgiaBDH entity)
		{
			this.SendPropertyChanging();
			entity.Thanhvien = null;
		}
		
		private void attach_Thamgiachuongtrinhs(Thamgiachuongtrinh entity)
		{
			this.SendPropertyChanging();
			entity.Thanhvien = this;
		}
		
		private void detach_Thamgiachuongtrinhs(Thamgiachuongtrinh entity)
		{
			this.SendPropertyChanging();
			entity.Thanhvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserLog")]
	public partial class UserLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Pass;
		
		private System.Nullable<bool> _Adminitrator;
		
		private System.Nullable<bool> _Tinhnguyen;
		
		private System.Nullable<bool> _Nhansu;
		
		private System.Nullable<bool> _Quankho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnAdminitratorChanging(System.Nullable<bool> value);
    partial void OnAdminitratorChanged();
    partial void OnTinhnguyenChanging(System.Nullable<bool> value);
    partial void OnTinhnguyenChanged();
    partial void OnNhansuChanging(System.Nullable<bool> value);
    partial void OnNhansuChanged();
    partial void OnQuankhoChanging(System.Nullable<bool> value);
    partial void OnQuankhoChanged();
    #endregion
		
		public UserLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(30)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adminitrator", DbType="Bit")]
		public System.Nullable<bool> Adminitrator
		{
			get
			{
				return this._Adminitrator;
			}
			set
			{
				if ((this._Adminitrator != value))
				{
					this.OnAdminitratorChanging(value);
					this.SendPropertyChanging();
					this._Adminitrator = value;
					this.SendPropertyChanged("Adminitrator");
					this.OnAdminitratorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhnguyen", DbType="Bit")]
		public System.Nullable<bool> Tinhnguyen
		{
			get
			{
				return this._Tinhnguyen;
			}
			set
			{
				if ((this._Tinhnguyen != value))
				{
					this.OnTinhnguyenChanging(value);
					this.SendPropertyChanging();
					this._Tinhnguyen = value;
					this.SendPropertyChanged("Tinhnguyen");
					this.OnTinhnguyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhansu", DbType="Bit")]
		public System.Nullable<bool> Nhansu
		{
			get
			{
				return this._Nhansu;
			}
			set
			{
				if ((this._Nhansu != value))
				{
					this.OnNhansuChanging(value);
					this.SendPropertyChanging();
					this._Nhansu = value;
					this.SendPropertyChanged("Nhansu");
					this.OnNhansuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quankho", DbType="Bit")]
		public System.Nullable<bool> Quankho
		{
			get
			{
				return this._Quankho;
			}
			set
			{
				if ((this._Quankho != value))
				{
					this.OnQuankhoChanging(value);
					this.SendPropertyChanging();
					this._Quankho = value;
					this.SendPropertyChanged("Quankho");
					this.OnQuankhoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class fu_DS_DoivienTheoKDVResult
	{
		
		private string _MSSV;
		
		private string _Hoten;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _Quequan;
		
		private string _Nganh;
		
		private string _Khoa;
		
		private string _KhoaDV;
		
		public fu_DS_DoivienTheoKDVResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					this._MSSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this._Hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this._Ngaysinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quequan", DbType="NVarChar(30)")]
		public string Quequan
		{
			get
			{
				return this._Quequan;
			}
			set
			{
				if ((this._Quequan != value))
				{
					this._Quequan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nganh", DbType="NVarChar(30)")]
		public string Nganh
		{
			get
			{
				return this._Nganh;
			}
			set
			{
				if ((this._Nganh != value))
				{
					this._Nganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="NVarChar(30)")]
		public string Khoa
		{
			get
			{
				return this._Khoa;
			}
			set
			{
				if ((this._Khoa != value))
				{
					this._Khoa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoaDV", DbType="NVarChar(30)")]
		public string KhoaDV
		{
			get
			{
				return this._KhoaDV;
			}
			set
			{
				if ((this._KhoaDV != value))
				{
					this._KhoaDV = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
